# Paths for input and output files

input_path = "../Test_Dataset/"  # Path where input SMILES files are located
file_pattern = "*.csv"  # File pattern for input files (e.g., "*.csv", "*.smi")
output_path = "../Test_FPS/"  # Path where output HDF5 files will be saved

# Morgan Count Fingerptint generation settings (Do not change anything, we have RDKit fingerprints by default, Changing this can cause error)
[morgan]
morgan_radius = 2  # Radius for Morgan fingerprints
morgan_fp_size = 1024  # Size of the Morgan fingerprint (e.g., 1024 bits)

# Whether to preprocess descriptors
[preprocess]


# Logging and error handling
[logging]
log_path = "logs/"  # Path where logs will be stored
log_level = "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)

# Parallel processing settings
[parallel]
num_workers = 4  # Number of parallel workers to use for processing (set to 1 for no parallelization)
