# General Configuration
data_path = "/path/to/dataset.h5"  # Path to the dataset
output_dir = "/path/to/output/directory"  # Path to save output files
val_data_path = "/path/to/validation_dataset.h5"  # Optional path to validation data (can be empty)
test = false  # Whether to run in test mode
plot_data = true  # Whether to plot data after processing

# Dimensionality Reduction Methods to Use
methods = ["UMAP", "t-SNE", "GTM", "PCA"]  # List of methods to apply

# PCA Configuration
n_components = 2  # Number of PCA components

# Nearest Neighbors Configuration
k_neighbors = [2, 5, 10, 20, 50]  # List of k values for nearest neighbors
k_hit = 20  # Number of nearest neighbors for hit calculation (must be in k_neighbors)

# Optimization Configuration
optimization_type = "insample"  # Options: "insample" or "outsample"
scaling = "standard"  # Scaling method, options: "standard", "minmax", etc.
similarity_metric = "euclidean"  # Similarity metric to use: "euclidean", "tanimoto"
sample_size = 2500  # Sample size for metrics calculation

# Logging Configuration
log_level = "INFO"  # Options: "DEBUG", "INFO", "WARNING", "ERROR"
